kind: Service
apiVersion: v1
metadata:
  name: nginx-deployment
  labels:
        app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
